services:
  app:
    container_name: kampaign-dev
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules
      - ./logs:/app/logs
      - ./tmp:/app/tmp
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm run dev"
    env_file:
      - .env